version: '3.4'

services:
  healthcareclaimsv1:
    image: ${DOCKER_REGISTRY-}healthcareclaimsv1
    build:
      context: .
      dockerfile: HealthcareClaims/Dockerfile

  healthcareclaimsv2:
    image: ${DOCKER_REGISTRY-}healthcareclaimsv2
    depends_on:
      - consul
    build:
      context: .
      dockerfile: HealthcareClaimsWithModules/Dockerfile

  claimssubmissionapi:
    image: ${DOCKER_REGISTRY-}claimssubmissionapi
    build:
      context: .
      dockerfile: ClaimsSubmission.Api/Dockerfile

  objectsstorage:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    ports:
      - "9000:9000"
    volumes:
      - objectstorage:/data
    command: server /data
    networks:
      - backtier

  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test*123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backtier

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    ports:
      - "8500:8500"
    volumes:
      - consulconfig:/config
      - consuldata:/data
    networks:
      - backtier

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    networks:
      - backtier

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - backtier

volumes: 
  pgdata:
    driver: local
  objectstorage:
    driver: local
  consulconfig:
    driver: local
  consuldata:
    driver: local
  elasticsearchdata:
    driver: local
